### ISSUE TITLE
更新sdk后导出报错

### ISSUE THREAD

**Issue by qingzhengxuegao** [wechat-miniprogram/minigame-tuanjie-transform-sdk#11]
package manager用git方式下载后，在导出包是时候会报错。
Exception: Invalid WebGL template path: C:/Program Files/Tuanjie/Hub/Editor/2022.3.2t6/Editor/Data/PlaybackEngines/WeixinMiniGameSupport\BuildTools\WebGLTemplates\D! Select a template in player settings.
UnityEditor.WeixinMiniGame.WeixinMiniGameBuildPostprocessor.CheckBuildPrerequisites () (at <b4e00c6a2d36445b981ecdd7705fc3d7>:0)
UnityEditor.WeixinMiniGame.WeixinMiniGameBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <b4e00c6a2d36445b981ecdd7705fc3d7>:0)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <d853ec3cefb8409dbbbcdb8fb94beb3d>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <d853ec3cefb8409dbbbcdb8fb94beb3d>:0)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
请问有解决方案吗？

**Comment by liuxinyumocn** [comment]
已修复问题，关闭issues。
另请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答。
