### ISSUE TITLE
这个跟 minigame-unity-webgl-transform 的区别是什么？

### ISSUE THREAD

**Issue by cacard** [wechat-miniprogram/minigame-tuanjie-transform-sdk#14]
如题。

**Comment by liuxinyumocn** [comment]
本仓库为插件包提供库，如需了解快适配方案请前往minigame-unity-webgl-transform阅读相关文档。
关闭issues。
请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答。
