### ISSUE TITLE
Mac 上压缩纹理卡死

### ISSUE THREAD

**Issue by zgc0911** [wechat-miniprogram/minigame-tuanjie-transform-sdk#15]
在Mac上执行压缩纹理，在【阶段2/2】中卡死
[TextToolDatas.zip](https://github.com/user-attachments/files/15896676/TextToolDatas.zip)

**Comment by liuxinyumocn** [comment]
请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答
