### ISSUE TITLE
GameGlobal.manager.font.getCommonFont 获取的是什么字体？

### ISSUE THREAD

**Issue by fengshangchao** [wechat-miniprogram/minigame-tuanjie-transform-sdk#17]
getCommonFont  获取的是微信的字体还是什么字体？有没有相关文档可以了解一下

**Comment by liuxinyumocn** [comment]
请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答
