### ISSUE TITLE
sdk中的类LoginOption在程序集 wx-runtime-editor定义,导致热更层存在WX.Login(new LoginOption())就无法运行

### ISSUE THREAD

**Issue by melontaro** [wechat-miniprogram/minigame-tuanjie-transform-sdk#19]
问题:
1,类LoginOption因为是在程序集 wx-runtime-editor中定义的;
2,我在使用了HybridCLR热更新,在热更层只要存在WX.Login(new LoginOption())unity编辑器就无法运行(即使没有任何地方调用这个接口),
3,只要把WX.Login(new LoginOption())注释掉就运行正常;
报错如下:
System.TypeLoadException: Could not load type of field 'ET.Client.WeiXinComponentSystem+<>c:<>9__3_1' (1) due to: Could not load file or assembly 'wx-runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
  at (wrapper managed-to-native) System.RuntimeTypeHandle.type_is_assignable_from(System.Type,System.Type)
  at System.RuntimeTypeHandle.CanCastTo (System.RuntimeType type, System.RuntimeType target) [0x00000] in <6aa56e57ab504395b555cf3ed50fa53d>:0 
  at System.RuntimeType.IsAssignableFrom (System.Type c) [0x00020] in <6aa56e57ab504395b555cf3ed50fa53d>:0 
  at ET.LSEntitySystemSingleton.Awake () [0x000ca] in D:\WorkSpace\Unity\WebGL\Unity\Assets\Scripts\Model\Share\LockStep\LSEntitySystemSingleton.cs:45 
  at ET.CodeTypes.CreateCode () [0x0002c] in D:\WorkSpace\Unity\WebGL\Unity\Assets\Scripts\Core\World\Module\Code\CodeTypes.cs:69 
  at ET.Entry.StartAsync () [0x00070] in D:\WorkSpace\Unity\WebGL\Unity\Assets\Scripts\Model\Share\Entry.cs:48 
  at ET.ETTask.GetResult () [0x00039] in D:\WorkSpace\Unity\WebGL\Unity\Assets\Scripts\ThirdParty\ETTask\ETTask.cs:126 
  at ET.ETTask.InnerCoroutine () [0x0001b] in D:\WorkSpace\Unity\WebGL\Unity\Assets\Scripts\ThirdParty\ETTask\ETTask.cs:71 
UnityEngine.Debug:LogError (object)
ET.UnityLogger:Error (string) (at Assets/Scripts/Loader/UnityLogger.cs:29)
ET.Log:Error (System.Exception) (at Assets/Scripts/Core/World/Module/Log/Log.cs:76)
ET.AsyncETVoidMethodBuilder:SetException (System.Exception) (at Assets/Scripts/ThirdParty/ETTask/AsyncETVoidMethodBuilder.cs:33)
ET.ETTask/<InnerCoroutine>d__10:MoveNext () (at Assets/Scripts/ThirdParty/ETTask/ETTask.cs:71)
ET.AsyncETVoidMethodBuilder:Start<ET.ETTask/<InnerCoroutine>d__10> (ET.ETTask/<InnerCoroutine>d__10&) (at Assets/Scripts/ThirdParty/ETTask/AsyncETVoidMethodBuilder.cs:68)
ET.ETTask:InnerCoroutine ()
ET.ETTask:Coroutine () (at Assets/Scripts/ThirdParty/ETTask/ETTask.cs:77)
ET.Entry:Start () (at Assets/Scripts/Model/Share/Entry.cs:28)
System.Reflection.MethodBase:Invoke (object,object[])
ET.StaticMethod:Run () (at Assets/Scripts/Core/Method/StaticMethod.cs:19)
ET.CodeLoader:Start () (at Assets/Scripts/Loader/CodeLoader.cs:103)
ET.Init/<StartAsync>d__1:MoveNext () (at Assets/Scripts/Loader/MonoBehaviour/Init.cs:40)
ET.StateMachineWrap`1<ET.Init/<StartAsync>d__1>:Run () (at Assets/Scripts/ThirdParty/ETTask/StateMachineWrap.cs:55)
ET.ETTask:SetResult () (at Assets/Scripts/ThirdParty/ETTask/ETTask.cs:145)
ET.ETAsyncTaskMethodBuilder:SetResult () (at Assets/Scripts/ThirdParty/ETTask/AsyncETTaskMethodBuilder.cs:47)
ET.ResourcesComponent/<CreatePackageAsync>d__3:MoveNext () (at Assets/Scripts/Loader/Resource/ResourcesComponent.cs:146)
ET.StateMachineWrap`1<ET.ResourcesComponent/<CreatePackageAsync>d__3>:Run () (at Assets/Scripts/ThirdParty/ETTask/StateMachineWrap.cs:55)
System.Threading.Tasks.TaskCompletionSource`1<object>:TrySetResult (object)
YooAsset.AsyncOperationBase:SetFinish () (at ./Library/PackageCache/com.tuyoogame.yooasset@2.1.1/Runtime/OperationSystem/AsyncOperationBase.cs:111)
YooAsset.OperationSystem:Update () (at ./Library/PackageCache/com.tuyoogame.yooasset@2.1.1/Runtime/OperationSystem/OperationSystem.cs:83)
YooAsset.YooAssets:Update () (at ./Library/PackageCache/com.tuyoogame.yooasset@2.1.1/Runtime/YooAssets.cs:84)
YooAsset.YooAssetsDriver:Update () (at ./Library/PackageCache/com.tuyoogame.yooasset@2.1.1/Runtime/YooAssetsDriver.cs:13)

**Comment by liuxinyumocn** [comment]
请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答

**Comment by AxingSB881** [comment]
之前用的2018的没啥问题，换到最新的也一样的，wx-runtime-editor是开发环境使用的，热更层只能选择这个引用。这个dll跟wx-runtime大差不差，我直接删了，然后wx-runtime的应用修改为Editor跟WebGL环境就编译通过了
