### ISSUE TITLE
使用tuanjie引擎导出正常，运行报错'createPath'

### ISSUE THREAD

**Issue by Zhaopengyang** [wechat-miniprogram/minigame-tuanjie-transform-sdk#6]
加载资源异常  Cannot read property 'createPath' of undefined TypeError: Cannot read property 'createPath' of undefined
start game fail:  TypeError: Cannot read property 'createPath' of undefined
MONO_WASM: instantiate_wasm_module() failed CompileError: WebAssembly.instantiate(): unexpected section <Exception> (enable with --experimental-wasm-eh) @+54576(env: macOS,mg,1.06.2402040; lib: 3.2.5)

导出正常，资源上传UOS正常，但是微信开发者工具打开之后报错

**Comment by liuxinyumocn** [comment]
已修复问题，关闭issues。
另请阁下前往微信Unity快适配方案主仓库发起新的issues：
https://github.com/wechat-miniprogram/minigame-unity-webgl-transform/issues

本仓库专为提供插件包后续将自动关闭issues问答。
